# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd
import numpy as np

"""STEP 1: Data Load aur Initial Split (90-10)"""

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

# Data Load
cancer = load_breast_cancer()
X = pd.DataFrame(cancer.data, columns=cancer.feature_names)
y = pd.Series(cancer.target)  # <-- 'y' ko Pandas Series banaya

# Step 1: Main Split (90% Train, 10% Test)
X_train_90, X_test_10, y_train_90, y_test_10 = train_test_split(
    X, y, test_size=0.10, random_state=42, stratify=y
)

# Ab .reset_index() bina kisi error ke chalega!
X_train_90 = X_train_90.reset_index(drop=True)
y_train_90 = y_train_90.reset_index(drop=True)
X_test_10 = X_test_10.reset_index(drop=True)
y_test_10 = y_test_10.reset_index(drop=True)

print(f"Total Rows in Train Data (90%): {len(X_train_90)}")
print(f"Total Rows in Test Data (10%) : {len(X_test_10)}")

from sklearn.model_selection import StratifiedKFold
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

# 1. K-Fold Setup (5 Folds)
kf = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

# 2. Base Models Dictionary
models = {
    'm1': DecisionTreeClassifier(random_state=42),
    'm2': LogisticRegression(max_iter=5000, random_state=42),
    'm3': KNeighborsClassifier()
}

# 3. Out-Of-Fold (OOF) Predictions store karne ke liye empty arrays (length = 512 rows)
oof_pred_m1 = np.zeros(len(X_train_90))
oof_pred_m2 = np.zeros(len(X_train_90))
oof_pred_m3 = np.zeros(len(X_train_90))

print("✅ K-Fold aur Base Models set ho gaye hain!")
print(f"OOF Prediction Arrays ka shape: {oof_pred_m1.shape}")

"""K-Fold Loop"""

# =========================================================
# STEP 3: Out-of-Fold (OOF) Predictions Collect Karna
# =========================================================

for train_idx, val_idx in kf.split(X_train_90, y_train_90):
    # Folds ke according Train aur Validation data alag karna
    X_tr, X_val = X_train_90.iloc[train_idx], X_train_90.iloc[val_idx]
    y_tr, y_val = y_train_90.iloc[train_idx], y_train_90.iloc[val_idx]

    # Model 1 (Decision Tree)
    models['m1'].fit(X_tr, y_tr)
    oof_pred_m1[val_idx] = models['m1'].predict(X_val)

    # Model 2 (Logistic Regression)
    models['m2'].fit(X_tr, y_tr)
    oof_pred_m2[val_idx] = models['m2'].predict(X_val)

    # Model 3 (KNN)
    models['m3'].fit(X_tr, y_tr)
    oof_pred_m3[val_idx] = models['m3'].predict(X_val)

# Packing: Teeno models ki predictions ko milakar Meta Dataset banana
meta_X_train = pd.DataFrame({
    'dt_pred': oof_pred_m1,
    'lr_pred': oof_pred_m2,
    'knn_pred': oof_pred_m3
})

print("✅ STEP 3 Complete: Meta-Model ka Training Dataset taiyar ho gaya!")
print("Meta Dataset ka Shape:", meta_X_train.shape)
print("\nMeta Dataset ki pehli 5 rows:")
print(meta_X_train.head())

"""train meta model

"""

# =========================================================
# STEP 4: Meta-Model Training
# =========================================================
from sklearn.ensemble import RandomForestClassifier

# 1. Meta-Model Initialize karna
meta_model = RandomForestClassifier(random_state=42)

# 2. Meta-Model ko (meta_X_train, y_train_90) par fit/train karna
meta_model.fit(meta_X_train, y_train_90)

print("🎉 STEP 4 Complete: Meta-Model successfully train ho gaya hai!")

"""base modelo training"""

# =========================================================
# STEP 5: Base Models Retraining (Full 90% Train Data)
# =========================================================

# Teeno base models ko poore 90% training data par fit/train karna
models['m1'].fit(X_train_90, y_train_90)
models['m2'].fit(X_train_90, y_train_90)
models['m3'].fit(X_train_90, y_train_90)

print("✅ STEP 5 Complete: Teeno Base Models poore 90% data par retrain ho gaye hain!")

# =========================================================
# STEP 6: Final Predictions & Evaluation (10% Test Data)
# =========================================================
from sklearn.metrics import accuracy_score

# 1. Base models se unseen test data par predictions lena
test_pred_m1 = models['m1'].predict(X_test_10)
test_pred_m2 = models['m2'].predict(X_test_10)
test_pred_m3 = models['m3'].predict(X_test_10)

# 2. Test predictions ko Meta-Dataset DataFrame mein pack karna
meta_X_test = pd.DataFrame({
    'dt_pred': test_pred_m1,
    'lr_pred': test_pred_m2,
    'knn_pred': test_pred_m3
})

# 3. Meta-Model se Final Predictions nikalna
final_predictions = meta_model.predict(meta_X_test)

# 4. Final Accuracy Score calculate karna
final_acc = accuracy_score(y_test_10, final_predictions)

print("🎯 STEP 6 Complete: Stacking Pipeline Successfully Executed!")
print(f"🔥 Final Stacking Model Accuracy on Test Data: {final_acc * 100:.2f}%")